---
title: "final project analysis script"
author: "the group"
date: "28 7 2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(dplyr)
library(ordinal)
library(StanHeaders)
library(rstan)
library(bridgesampling)
library(shiny)
library(shinystan)
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
set.seed(123)


```

## read data
```{r}
#--Set APA theme to use with ggplot
theme_set(theme_bw(18)+
            theme(panel.grid.major=element_blank(),
                  panel.grid.minor=element_blank(),
                  panel.border=element_blank(),
                  strip.background=element_blank(),
                  strip.text = element_text(face="bold"),
                  axis.line=element_line(),
                  text=element_text(family="serif")))

all_data <- read.csv("./results_260_XPLab-2021-Group3_974857.csv")

# total number of participants
n_participants_raw <- all_data %>% 
  group_by(submission_id) %>% 
  summarise() %>% 
  nrow(.)  
n_participants_raw

# look at data
all_data %>% tbl_df %>% rmarkdown::paged_table()
```
# Cleaning data
```{r}
#select data to analyse. drop columns endTime(5), experiment_id(10), startDate(21), startTime(22), timeSpent(23), trial_number(25)
analyse_data <- all_data[-c(5, 10, 21, 22, 23, 25)]
#exclude data where understanding check was wrong
analyse_data <- analyse_data %>% 
  group_by(submission_id) %>% 
  filter(all( ( trial_name != "understanding_check" | ((response_claim1 == "correct" &  response_claim2 == "incorrect" & response_claim3 == "incorrect" & response_claim4 == "incorrect")))))
# look how many were excluded bco understanding check
n_excluded <- n_participants_raw - analyse_data %>% 
  group_by(submission_id) %>% 
  summarise() %>% 
  nrow(.)  
n_excluded

# change ingroup norm to 1 (do nothing) or 0 (call police)
analyse_data <- analyse_data %>%
  mutate(ingroup_norm_new = ifelse(grepl("chose to do nothing and leave the robber alone.$",ingroup_norm),1,ifelse(grepl("chose to call the police and report the robber.$",ingroup_norm),-1,NA)))

# drop data of understanding check and old ingroup norm coding
analyse_data <- subset(analyse_data, select = -c(expected_claim1, expected_claim2, expected_claim3, expected_claim4, response_claim1, response_claim2, response_claim3, response_claim4, ingroup_norm))
# exclude questions of understanding check
analyse_data <- analyse_data[analyse_data$trial_name != "custom understanding check", ]    

# new labels for better understanding
analyse_data <- mutate(analyse_data, condition = ifelse(ingroup_norm_new ==0 & both_norms_shown ==0, "Ingroup norm favoured calling police, only ingroup norm shown",
                                                  ifelse(ingroup_norm_new ==1 & both_norms_shown==0, "Ingroup norm favoured leaving robber alone, only ingroup norm shown",
                                                         ifelse(ingroup_norm_new ==1 & both_norms_shown==1, "Ingroup norm favoured leaving robber alone, both norms shown",
                                                                ifelse(ingroup_norm_new ==0 & both_norms_shown ==1,"Ingroup norm favoured calling the police, both norms shown",
                                                                       NA)))))
# look at data
analyse_data %>% tbl_df %>% rmarkdown::paged_table()
```

# data wrangling
```{r}
# make wider
analyse_data <- pivot_wider(analyse_data,
    names_from = trial_name,
    values_from = response
  )

analyse_data <- analyse_data %>% 
  group_by(submission_id) %>%
    summarise_each(funs(toString(na.omit(.))))

#rename column into usable name
analyse_data <- analyse_data %>%
  rename(
    moral_dilemma = "moral dilemma"
  )
analyse_data <- as.data.frame(analyse_data)

    
#change response to moral dilemma
#def call the police = 1
# def not call the police = 6
for(i in 1:nrow(analyse_data)){
  if(analyse_data[i,"moral_dilemma"] == "Definitely call the police and report the robber"){
  analyse_data[i,"moral_dilemma"]= 1
  } else if (analyse_data[i,"moral_dilemma"] == "Very likely call the police and report the robber"){
  analyse_data[i,"moral_dilemma"]= 2
  } else if (analyse_data[i,"moral_dilemma"] == "Probably call the police and report the robber"){
  analyse_data[i,"moral_dilemma"]= 3
  } else if (analyse_data[i,"moral_dilemma"] == "Probably do nothing and the leave the robber alone"){
    analyse_data[i,"moral_dilemma"]= 4
  } else if (analyse_data[i,"moral_dilemma"] == "Very likely do nothing and the leave the robber alone"){
    analyse_data[i,"moral_dilemma"]= 5
  } else if (analyse_data[i,"moral_dilemma"] == "Definitely do nothing and leave the robber alone"){
    analyse_data[i,"moral_dilemma"]= 6}

}

# code pro and anti group identification to 0 and 1
for(i in 1:nrow(analyse_data)){
  if(analyse_data[i,"identification_pro"] == 5 | analyse_data[i,"identification_pro"] == 6 | analyse_data[i,"identification_pro"] == 7){
  analyse_data[i,"identification_pro"]<- 1
  } else {
    analyse_data[i,"identification_pro"] <- 0 
  }
}
for(i in 1:nrow(analyse_data)){
  if(analyse_data[i,"identification_anti"] == 1 | analyse_data[i,"identification_anti"] == 2 | analyse_data[i,"identification_anti"] == 3){
  analyse_data[i,"identification_anti"]<- 1
  } else {
    analyse_data[i,"identification_anti"] <- 0 
  }
}

n_participants_cleaned <- nrow(analyse_data)

# add columns representing ingroup and outgroup of participant
# if participant was neutral about statement, exclude their data
analyse_data <- analyse_data %>%
  mutate(ingroup = ifelse(analyse_data$`statement rating` >= 1,"pro", ifelse(analyse_data$`statement rating` < 0, "anti", "exclude"))) %>%
  mutate(outgroup = ifelse(analyse_data$`statement rating` >= 1,"anti", ifelse(analyse_data$`statement rating` < 0, "pro", "exclude")))
analyse_data %>% tbl_df %>% rmarkdown::paged_table()

analyse_data <- analyse_data %>%
  filter(ingroup != "exclude")

# look how many were excluded bco neutral statement rating
n_excluded_statement <- n_participants_cleaned- nrow(analyse_data) 
n_excluded_statement
  
# add columns to include influence of identification in model:
# column "ingroup_agree" is 1 if participant identifies with ingroup and 0 if not 
# column "ingroup disagree" is 1 if participant does not identify with outgroup and 1 otherwise
analyse_data <- analyse_data %>%
  mutate(ingroup_agree = ifelse( ((analyse_data$ingroup == "pro" & analyse_data$identification_pro == 1) | (analyse_data$ingroup == "anti" & analyse_data$identification_anti == 1)), 1, 0)) %>%
  mutate(outgroup_disagree = ifelse( ((analyse_data$outgroup == "pro" & analyse_data$identification_pro == 0) | (analyse_data$outgroup == "anti" & analyse_data$identification_anti == 0)), 1, 0))
analyse_data %>% tbl_df %>% rmarkdown::paged_table()

# code issues as numbers 0-8
for(i in 1:nrow(cleaned_data)){
  if(cleaned_data[i,"issue"] == "Gun control"){
  cleaned_data[i,"issue"]= 0
  } else if (cleaned_data[i,"issue"] == "Feminism"){
  cleaned_data[i,"issue"]= 1
  } else if (cleaned_data[i,"issue"] == "Joe Biden"){
  cleaned_data[i,"issue"]= 2
  } else if (cleaned_data[i,"issue"] == "Immigration and Dreamers"){
    cleaned_data[i,"issue"]= 3
  } else if (cleaned_data[i,"issue"] == "Transgender rights"){
    cleaned_data[i,"issue"]= 4
  } else if (cleaned_data[i,"issue"] == "Drug legalization"){
    cleaned_data[i,"issue"]= 5
  } else if (cleaned_data[i,"issue"] == "Colin Kaepernick kneeling during the national anthem"){
    cleaned_data[i,"issue"]= 6
  } else if (cleaned_data[i,"issue"] == "Buying and wearing fur"){
    cleaned_data[i,"issue"]= 7
  } else if (cleaned_data[i,"issue"] == "Taxing religious organizations"){
    cleaned_data[i,"issue"]= 8
  }  }

# safe data in this format for later
cleaned_data <- analyse_data
# look at data
cleaned_data %>% tbl_df %>% rmarkdown::paged_table()

```
# Analysis
```{r}
# #Frequentist Analysis----------------
# length(analyse_data$ingroup_norm_new)
# length(analyse_data$both_norms_shown)
# 
#make all value numeric
analyse_data <- mutate_all(analyse_data, function(x) as.numeric(as.character(x)))
ordinal_1 <- clm(as.factor(moral_dilemma)~ ingroup_norm_new*both_norms_shown, data=analyse_data)

# 
source("functions/produce_mean_and_count_bar_plot.R")
plot_1 <- produce_mean_and_count_bar_plot(analyse_data, bar_width_means=0.5, bar_width_response=0.3)
ggsave(file="plot_1.png", plot=plot_1, width=190, height = 110, units="mm")  

#Bayesian analysis------------
#Prepare data for stan.
analyse_data <- analyse_data %>%
  select(moral_dilemma, ingroup_norm_new, both_norms_shown, identification_pro, identification_anti) %>% #select relevant columns
  mutate(identification_pro = ifelse(is.na(identification_pro), 1, identification_pro), #For the experiment we assumed that participants identified with the ingroup and not with the outgroup.
         identification_anti = ifelse(is.na(identification_anti), 1, identification_anti)
         )
stan_data_all <- as.list(c(analyse_data, N = dim(analyse_data)[1]))
#stan_data1 <- as.list(c(filter(analyse_data), N=sum(analyse_data)))

#--Fit models
fit_SCT_all <- rstan::stan(file = "stan_models/SCT.stan", data=stan_data_all, iter=10000, chains=4, seed = 123, control=list(adapt_delta = 0.99))
fit_herding_all <- rstan::stan(file = "stan_models/herding.stan", data=stan_data_all, iter=10000, chains=4, control=list(adapt_delta = 0.99))

#--Compare models using Bayes Factors
marg_lik_SCT_all <- bridge_sampler(samples = fit_SCT_all)
marg_lik_herding_all <- bridge_sampler(samples = fit_herding_all)
bf(marg_lik_herding_all,marg_lik_SCT_all)


#Create prior-posterior plots-------
# source("functions/plot_priors_posteriors.R")
# 
# #Plot which issues people cared about and the extent to which they agreed with them-------
# issue_plot_3 <- ggplot(cleaned_data, aes(x=factor(issue,labels = c(#"Gun control", 
#                                                  "Feminism",
#                                                  #"Joe Biden",
#                                                  #"Immigration and Dreamers",
#                                                  "Transgender rights",
#                                                  #"Drug legalization",
#                                                  "Colin Kaepernick kneeling during the national anthem",
#                                                  "Buying and wearing fur"
#                                                  #"Taxing religious organizations"
#                                                  )
#                                                 ),
#                   y = "statement rating", 
#                   colour = factor(issue),
#                   fill = factor(issue))) + 
#   geom_dotplot(binaxis = "y", stackdir = "center", binwidth = 0.15) +
#   labs(x = "Issue", y="Agreement") + 
#   guides(color=FALSE, fill=FALSE)+
#   scale_y_continuous(breaks=c(0,5,10), labels = c("Strongly disagree", "Neutral", "Strongly agree"))
# ggsave("issue_plot_3.png", issue_plot_3, width=34, height=13, units="cm")
# 
# issue_plot_4 <- ggplot(cleaned_data, aes(x=factor(issue#, #labels = c("Gun \n control", 
# #                                                                 "Feminism", 
# #                                                                 "Joe \n Biden", 
# #                                                                 "Immigration",
# #                                                                 "Transgender \n rights",
# #                                                                 "Drug \n legalization",
# #                                                                 "Colin \n Kaepernick",
# #                                                                 "Fur is \n wrong",
# #                                                                 "Taxing religious organizations")
# ),
#                                   y = issue, 
#                                   colour = factor(issue),
#                                   fill = factor(issue))) + 
#   geom_dotplot(binaxis = "y", stackdir = "center", binwidth = 0.15) +
#   labs(x = "Issue", y="Agreement") + 
#   guides(color=FALSE, fill=FALSE)+
#   scale_y_continuous(breaks=c(0,5,10), labels = c("Strongly disagree", "Neutral", "Strongly agree"))
# ggsave("issue_plot_4.png", issue_plot_4, width=34, height=13, units="cm")
```

